"""AcoustiForge contracts package."""

from .pcm import AudioMetadata, ChannelLayout, PCMBlock
from .validation import (
    AcoustiForgeError,
    ChannelMismatchError,
    CycleDetectedError,
    DuplicateEdgeError,
    FrozenGraphError,
    IncompatibleNodeError,
    InvalidBlockSizeError,
    InvalidChannelCountError,
    InvalidGraphError,
    InvalidParameterError,
    InvalidSampleFormatError,
    InvalidSampleRateError,
    MalformedBufferError,
    NonContiguousBufferError,
    NonFiniteValueError,
    UnconnectedPortError,
    UnstableFilterError,
    validate_metadata,
    validate_pcm_buffer,
    validate_pipeline_link,
)

__all__ = [
    "AcoustiForgeError",
    "AudioMetadata",
    "ChannelLayout",
    "ChannelMismatchError",
    "CycleDetectedError",
    "DuplicateEdgeError",
    "FrozenGraphError",
    "IncompatibleNodeError",
    "InvalidBlockSizeError",
    "InvalidChannelCountError",
    "InvalidGraphError",
    "InvalidParameterError",
    "InvalidSampleFormatError",
    "InvalidSampleRateError",
    "MalformedBufferError",
    "NonContiguousBufferError",
    "NonFiniteValueError",
    "PCMBlock",
    "UnconnectedPortError",
    "UnstableFilterError",
    "validate_metadata",
    "validate_pcm_buffer",
    "validate_pipeline_link",
]
