"""AcoustiForge — Hardware-Independent Computational Audio Platform.

Acoustic Compute Engine (ACE) Core Packages.
"""

from .contracts import (
    AcoustiForgeError,
    AudioMetadata,
    ChannelLayout,
    ChannelMismatchError,
    CycleDetectedError,
    DuplicateEdgeError,
    FrozenGraphError,
    IncompatibleNodeError,
    InvalidBlockSizeError,
    InvalidChannelCountError,
    InvalidGraphError,
    InvalidParameterError,
    InvalidSampleFormatError,
    InvalidSampleRateError,
    MalformedBufferError,
    NonContiguousBufferError,
    NonFiniteValueError,
    PCMBlock,
    UnconnectedPortError,
    UnstableFilterError,
    validate_metadata,
    validate_pcm_buffer,
    validate_pipeline_link,
)
from .nodes import (
    BaseProcessingNode,
    BiquadCoefficients,
    BiquadNode,
    DelayNode,
    FilterType,
    GainNode,
    PassThroughNode,
    calculate_biquad_coefficients,
)
from .engine import ReferencePipeline, SequentialPipeline
from .graph import (
    ComputeGraph,
    Edge,
    GraphLifecycle,
    Port,
    PortDirection,
    PortShape,
    PortType,
)

__version__ = "0.1.0"

__all__ = [
    "AcoustiForgeError",
    "AudioMetadata",
    "BaseProcessingNode",
    "BiquadCoefficients",
    "BiquadNode",
    "ChannelLayout",
    "ChannelMismatchError",
    "ComputeGraph",
    "CycleDetectedError",
    "DelayNode",
    "DuplicateEdgeError",
    "Edge",
    "FilterType",
    "FrozenGraphError",
    "GainNode",
    "GraphLifecycle",
    "IncompatibleNodeError",
    "InvalidBlockSizeError",
    "InvalidChannelCountError",
    "InvalidGraphError",
    "InvalidParameterError",
    "InvalidSampleFormatError",
    "InvalidSampleRateError",
    "MalformedBufferError",
    "NonContiguousBufferError",
    "NonFiniteValueError",
    "PCMBlock",
    "PassThroughNode",
    "Port",
    "PortDirection",
    "PortShape",
    "PortType",
    "ReferencePipeline",
    "SequentialPipeline",
    "UnconnectedPortError",
    "UnstableFilterError",
    "__version__",
    "calculate_biquad_coefficients",
    "validate_metadata",
    "validate_pcm_buffer",
    "validate_pipeline_link",
]
